apiVersion: batch/v1
kind: Job
metadata:
  name: config-postgres-db
spec:
  template:
    spec:
      containers:
      - name: postgres-job
        image: postgres:15
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db
        - name: PGHOST
          value: postgres-svc
        command:
        - sh
        - -c
        - |
          echo "Waiting for Postgres to be ready..."
          until pg_isready -h "$POSTGRES_HOST" -U "$POSTGRES_USER"; do
            sleep 2
          done
          echo "Postgres is ready, creating table..."

          psql <<EOF
          CREATE TABLE IF NOT EXISTS feedback (
            id SERIAL PRIMARY KEY,
            user_id TEXT NOT NULL,
            timestamp TEXT NOT NULL,
            conversation_id TEXT NOT NULL,
            user_question TEXT NOT NULL,
            llm_response TEXT NOT NULL,
            sentiment INTEGER,
            user_feedback TEXT,
            categories TEXT[]
          );
          EOF
      restartPolicy: OnFailure
