name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Check Python Version
      run: python --version
    - name: Install PDM
      run: pip install --user pdm
    - name: Run Unit Tests
      run: |
        cd src/harvester
        pdm install
        pdm run python -m pytest tests/unit -v
